---
title: "Syuchet: A Text Mining Infrastructure for Plot and Sentment Analysis in R"
author: "Matthew Jockers"
date: "January 24, 2015"
output: pdf_document
---
# Introduction
This vignette gives a short introduction to plot arc and sentiment modeling in R utilizing the text mining functions provided by the Syuzhet package.  Methods for text import, sentiment extraction, and plot arc modeling are described.  This package was originally designed for applications in literary analysis where we wish to derive the fundamental plot arc of a novel, for example, in order to visualize how the narrative is constructed.  Specifically, we are interested in what the Russian formalist Vladimir Propp defined as the narrative's \emph{syuzhet} (the organization of the narrative) as opposed to the \emph{fabula} (raw elements of the story).  Syuzhet is concerned with  the linear progression of the narrative from beginning (first page) to the end (last page), whereas fabula is concerned with the specific events of the story which may or may not be related in chronological order.  When we study the \emph{fabula}, we may, for example, wish to reconstructs a narrative that involves a series of flashbacks to prior events into chronological order so as to better understand the experience of the characters.  Syuzhet is less concerned with the order of the fictional events and more interested in the manner in which the author presents those events to us as a linear narrative.  

Consider the technique that radio personality Paul Harvey used in his iconic radio show "The Rest of the Story."  In each story, Harvey would hold back certain key elements until the very end of the program.  The story would appear to have reached its conclusion, and then Harvey would say, "and now, the rest of the story."  At this point, he would reveal the held back information and the reader would then be able to reconstruct the entire fabula.  The effect (and affect) of Harvey’s technique, his particular syuzhet, was usually stunning and pleasantly surprising.  Had the story been told in simple chronological order, it would have been bland and perhaps even boring.  What gave Harvey's show power was his narrative technique.  

This power was largely derived from the organization of the narrative elements and the manner in which Harvey offered listeners clues and then used narrative and language to evoke both curiosity and emotional response.  What Harvey said and how he said it, were critical elements to the overall effect of the story.  

Harvey's success was in finding and mastering a particular style of plot, a plot that has much in common with those found in mystery and detective fiction.  A series of clues is presented along side a series of mis-directions and the mystery is ultimately resolved in some grand reveal that in some ways defies expectations and in others makes perfect sense, so that readers are left wondering how they missed it.

But this is just one among many possible plots.  Countless scholars and non-scholars have pontificated for years about the idea that there might exist some finite set of fundamental or archetypal plot shapes.  One of the more recent and famous/infamous of these scholars is Christopher Booker whose 2004 book, titled \emph{The Seven Basic Plots: Why We Tell Stories}, argues for a Jungian inspired understanding of plot in terms of seven basic archetypes.  Booker's work appear strongly influenced by prior work describing plot in terms of different types of conflict.  These core conflicts will be familiar to students of literature as such constructions as man vs. man, man against nature, man vs. society, etc.  

Other scholars have offered other numbers.  William Foster-Harris has argued in favor of three basic patterns of plot \emph{The Basic Patterns of Plot}\footnote{Foster-Harris. The Basic Patterns of Plot. Norman: University of Oklahoma Press, 1959.}; Ronald B. Tobias has argued for twenty\footnote{Tobias, Ronald B. 20 Master Plots. Cincinnati: Writer’s Digest Books, 1993.}, and Georges Polti claims that there are thirty six\footnote{The Thirty-Six Dramatic Situations. trans. Lucille Ray}.  So the story goes.

All of these discussions about plot typically involve some discussion of story's central conflict.  I consider discussions of conflict to be more appropriately classified under the category of fabula.  Many of these same discussions also frequently explore the flow or trajectory of the narrative and these I consider to be appropriately categorized as discussion of the syuzhet. Very often these discussion engage visualization in order to explore and convey the "movement" of the narrative.  Perhaps the best example of this is offered by Kurt Vonnegut.  